### ISSUE TITLE
No way to load a saved state

### ISSUE THREAD

**Issue by el0911** [keermanish/example-react-page-maker#1]
Am trying to load the canvas with a previously saved state but no available function for that

**Comment by keermanish** [comment]
Hello @virgincodes 

You can populate the saved state through `initialElements` props to canvas.
https://github.com/keermanish/example-react-page-maker/blob/master/src/App.js#L59

Also, make sure you are taking state value from `state.getStorableState` method if you planning to parse it to a string.

Hope that helps!

**Comment by el0911** [comment]
State.getstorablestate method when was that added?

**Comment by keermanish** [comment]
It was added in 1.1.14 and unfortunately I missed to update the documentation around it.

That was my bad but anyways I'm working on new documentation and this has been covered, doc is almost ready, in day or two I LL publish it.

Reference - https://github.com/keermanish/react-page-maker/blob/feature/support-field-rud-operartions-state/README.md#state

**Comment by el0911** [comment]
Ok I've seen it but it's only getting the state of my parent element it isnt getting info about dropzone children/fields

**Comment by el0911** [comment]
ok update, the `state.getStorableState ` works perfectly, the only issue i had was that in the `draggableLayout `components for grids , the dropzones inside where not inheriting the `initialelements `prop from the parent component so i had to edit it to accommodate that , here is my updated code i  used a function `analyse()` with the argument of the parentID and search the `initialelements `available and match them to their  parentId and return the component.

But thanks anyway this library has been helpful 

```

import React from 'react';
import PropTypes from 'prop-types';
import { Row, Col } from 'reactstrap';
import { Draggable, Dropzone } from '../../react-page-maker/src';

const DraggableLayoutR1C2 = (props) => {
	// make sure you are passing `parentID` prop to dropzone
	// it help to mainatain the state to meta data
	const { showBasicContent, showPreview, id, initialElements, ...rest } = props;

	console.log(initialElements);

	if (showBasicContent) {
		return (
			<Draggable {...props}>
				<span>{rest.name}</span>
			</Draggable>
		);
	}

	const _onDrop = (data, cb) => {
		if (data.payload && data.payload.dataAlreadySet) {
			return cb(data);
		}

		// get actual data. It can be async call or some modal to fetch data
		const name = window.prompt('Enter name of field');

		const result = cb({
			...data,
			name: name || data.name,
			id: name || data.id,
			payload: {
				...data.payload,
				dataAlreadySet: true // just a flag to avoid multiple prompt
			}
		});
	};

	if (showPreview) {
		return (
			<div>
				<div className="mt-3">
					<Row className="row">
						<Col sm="6">{rest.childNode['canvas-1-1']}</Col>
						<Col sm="6">{rest.childNode['canvas-1-2']}</Col>
					</Row>
				</div>
			</div>
		);
	}

  const analyse = (parentID)=>{
     
    const child = 	initialElements.find((element) => {
      return element.dropzoneID == parentID;
    })

    if (child) {
      return [child]
    }
    
  }


	return (
		<Draggable {...props}>
			<span>{rest.name}</span>
			<div className="mt-3">
				<Row className="row">
					<Col sm="6">
						<Dropzone
							initialElements={  analyse("canvas-1-1") }
							parentID={id}
							id="canvas-1-1"
							onDrop={_onDrop}
							placeholder="Drop Here"
						/>
					</Col>
					<Col sm="6">
						<Dropzone
							initialElements={analyse("canvas-1-2")}
							parentID={id}
							id="canvas-1-2"
							onDrop={_onDrop}
							placeholder="Drop Here"
						/>
					</Col>
				</Row>
			</div>
		</Draggable>
	);
};

DraggableLayoutR1C2.propTypes = {
	id: PropTypes.string.isRequired,
	showBasicContent: PropTypes.bool.isRequired
};

export default DraggableLayoutR1C2;

```

**Comment by keermanish** [comment]
That's correct.

Unfortunately there is no easy way for lib to differentiate the initialElements of each dropzone, hence we have to write some filter function to separate out the initialElements of respective dropzone.

But thanks you brought this up, may be I'll rethink on this and try to make more simpler.
