### ISSUE TITLE
The row dropzone doesn't keep intialElements items inside

### ISSUE THREAD

**Issue by hosnyben** [keermanish/example-react-page-maker#8]
To be more descriptive, please follow those steps and you'll notice it from your side too. You can try ir in the demo also.

1.  Drop 1 by 2 Grid Layout (Let's Call it ROW1)
2. Drop inside each column of it a random element
3. Drop **another** 1 by 2 Grid Layout (ROW 2) in the main canvas
4. Drag the ROW1 inside of a dropzone of the new ROW2

You'll notice that the row lost the element inside, but in the Preview it still

**Comment by keermanish** [comment]
Thanks for pointing out.
The issue should be fixed with latest release.

also, [example](https://example-react-page-make.netlify.app/) is updated with these new changes.
